<?php

namespace OPM\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BARepository extends EntityRepository
{
}
