<?php

namespace OPM\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserCentresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCentresRepository extends EntityRepository
{
}
