opm_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: OPMUserBundle:Default:index }
    
opm_user_ajoutuser:
    path:     /ajoutuser
    defaults: { _controller: OPMUserBundle:AjoutUser:index }

opm_user_add:
    path:     /add
    defaults: { _controller: OPMUserBundle:Default:add }