<?php

namespace OPM\PerdiemsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BANQUESRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BANQUESRepository extends EntityRepository
{
}
