<?php

namespace OPM\PerdiemsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PERDIEMSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PERDIEMSRepository extends EntityRepository
{
}
